name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Added"
    labels:
      - "feature"
      - "enhancement"
  - title: "Fixed"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "feature"
      - "feat"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "chore"
  default: patch
autolabeler:
  - label: "chore"
    files:
      - "*.md"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
template: |
  ## Changed

  $CHANGES
