name: svg_to_avd
description: A library and CLI to convert SVG into Android Vector Drawable
version: 0.0.3
homepage: https://github.com/JCQuintas/svg_to_avd

executables:
  svgtoavd:
  svg_to_avd: svgtoavd

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.2
  path: ^1.8.3
  xml: ^6.2.2

dev_dependencies:
  dart_code_metrics: ^5.4.0
  lints: ^2.0.1
  test: ^1.20.1
  test_process: ^2.0.3
