name: svg_to_avd
description: A library and CLI to convert SVG into Android Vector Drawable
version: 0.0.2
homepage: https://github.com/JCQuintas/svg_to_avd

executables:
  svgtoavd:
  svg_to_avd: svgtoavd

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  args: ^2.3.0
  path: ^1.8.1
  xml: ^6.0.1

dev_dependencies:
  dart_code_metrics: ^4.14.0
  lints: ^1.0.0
  test: ^1.20.1
  test_process: ^2.0.2
