name: svg_to_avd
description: Converts SVG to Vector Drawable.
version: 1.0.0
homepage: https://github.com/JCQuintas/svg_to_avd

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  path: ^1.8.1
  xml: ^6.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1

